### ISSUE TITLE
Suggestion: Demo

### ISSUE THREAD

**Issue by sbrl** [giraysam/viiny-dragger#1]
A demo would be nice to show people how the library works.

**Comment by giraysam** [comment]
yes i will add a demo page coming soon.

**Comment by sbrl** [comment]
Awesome :D

**Comment by giraysam** [comment]
i have created a demo page and added a few examples. i will add another examples.

you can see it from this link. http://giraysam.github.io/viiny-dragger/

**Comment by sbrl** [comment]
Awesome. This library looks absolutely amazing! You've got yourself a star :star2: and a tweet :bird: 

**Update:** Link to tweet: https://twitter.com/SBRLabs/status/681908336946720768

**Comment by giraysam** [comment]
Thank you so much ;)

**Comment by sbrl** [comment]
No problem - great libraries deserve to be noticed :D
